name: Run tests
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: mlugg/setup-zig@v2
        with:
          version: "0.15.2"
          use-tool-cache: true

      - name: Run Tests
        run: |
          ./test.sh
